import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import CommandPalette from "../components/CommandPalette";

export default function Home() {
  return (
    <div className={"bg-[#FCFCFC] min-h-full flex items-center flex-col"}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CommandPalette />

      <div className="flex-1 flex items-center text-gray-600">
        Press{" "}
        <span className="bg-gray-200 mx-2 inline-block  py-[1px]  px-2 rounded text-gray-700">
          cmd
        </span>{" "}
        +{" "}
        <span className="bg-gray-200 mx-2 inline-block  py-[1px]  px-2 rounded text-gray-700">
          k
        </span>{" "}
        to open command palette
      </div>

      <footer className="p-4 w-full flex justify-center">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          className="flex items-center"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
